spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: userdb
    password: userpass

  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: false
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        ddl-auto: update

    defer-datasource-initialization: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enable: true
    baseline-on-migrate: false
    user: userdb
    password: userpass
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    locations: classpath:db/migration
    depends-on: entityManagerFactory
    schemas: public

logging:
  level:
    root: info
    br:
      com:
        itau: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080
  servlet:
    contextPath: "/api"
    session:
      timeout: 30m
  contextPath: "/api"
user:
  car:
    api:
      jwtSecret: userCarApiSecretKey
      jwtExpirationMinutes: 60


info:
  app:
    name: Spring Boot 2 actuator Application

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
      path: "/api-docs"