spring:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user_car
    username: root
    password: root

  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        ddl-auto: update

  flyway:
    enable: true
    baseline-on-migrate: true
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/db_user_car
    locations: classpath:db/migration

logging:
  level:
    root: info
    br:
      com:
        itau: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
user:
  car:
    api:
      jwtSecret: todoSecretKey
      jwtExpirationMinutes: 5


info:
  app:
    name: Spring Boot 2 actuator Application

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
      path: "/api-docs"