apiVersion: v1
kind: Service
metadata:
  name: user-car-api-service
spec:
  type: LoadBalancer
  selector:
    app: user-car-api
  ports:
    - port: 8081
      targetPort: 8081
  externalIPs:
    - 100.26.174.10