apiVersion: v1
kind: Service
metadata:
  name: user-car-api-service
spec:
  type: LoadBalancer
  selector:
    app: user-car-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  externalIPs:
    - 54.243.227.95