#!/usr/bin/env groovy
pipeline {
    agent any
    tools {
        maven 'Maven 3.9.4'
        jdk 'OpenJDK'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage("Build Image") {
            steps {
                script {
                    dockerapp = docker.build("cassianoricardo/user-car-api:${env.BUILD_ID}")
                }
            }
        }
        stage ('Push Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}