#!/usr/bin/env groovy
pipeline {
    agent any
    tools {
        maven 'Maven 3.9.4'
        jdk 'OpenJDK'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage("Build Image") {
            steps {
                script {
                    dockerapp = docker.build("user-car-api:${env.BUILD_ID}")
                }
            }
        }
        stage ('Push Image') {
                steps {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', 'cassiano28') {
                            dockerapp.push('latest')
                            dockerapp.push("${env.BUILD_ID}")
                        }
                    }
                }
        }
    }
}