#!/usr/bin/env groovy
pipeline {
    agent any
    tools {
        maven 'Maven 3.9.4'
        jdk 'OpenJDK'
    }
    stages {
        stage("Deployment") {
            steps {
                   sh 'sudo ufw allow 22'
            }
        }
    }
}